title: Paulo Zirlis # your name (or website title) here
logo: "/images/grad-pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A Data Scientist curious about human behaviour
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/paulo-zirlis/">LinkedIn Profile</a> 
  <br><br>
  <a href="https://https://github.com/pzirlis">Github Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
